version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    restart: always
    healthcheck:
      test: pg_isready -U ${POSTGRES_USERNAME}

  migrations:
    container_name: migrations
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run migration:run

  backend:
    container_name: backend
    build:
      context: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: always
    depends_on:
      - migrations
